export default [
  {
    fields: {
      id: 1,
      type: "pinza",
      name: "pinzafied margherita",
      category: "vegetarian",
      ingredients:
        "Tomato Sauce, Cherry Tomato, Burrata (Burrata Cheese is not baked and served fresh), Basil",
      pirce: 20,
      amount: 1,
      featuredImg: "/Images/shop-pinza-1.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 2,
      type: "pinza",
      category: "vegetarian",
      name: "Margherita 'The Classic' ",
      ingredients: "Tomato Sauce, Mozzarella, Basil, Oregano",
      pirce: 25,
      amount: 1,
      featuredImg: "/Images/shop-pinza-2.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 3,
      type: "pinza",
      category: "meat",
      name: "Tika Tika",
      ingredients:
        "Tomato Sauce, Mozzarella cheese, Chicken Tikka, Green Peppers, Onions, Curry leaves, Coriander, topped with Mango Salsa and Raita Sauce on the side",
      pirce: 15,
      amount: 1,
      featuredImg: "/Images/shop-pinza-3.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 4,
      type: "pinza",
      category: "vegetarian",
      name: "Supremo",
      ingredients:
        "Spicy Tomato Sauce, Mozzarella cheese, Pulled Beef, Pepperoni, Spianata, Bacon, Onions, Green Peppers, topped with Chili Flakes.",
      pirce: 23,
      amount: 1,
      featuredImg: "/Images/shop-pinza-4.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 5,
      type: "pinza",
      category: "meat",
      name: "The Smokin Turkey Pinza",
      ingredients:
        "Mozzarella cheese, The Mattar Farm Smoked Turkey, Caramelized Onions, topped with Burrata Cheese, Basil and Crushed Black Pepper.",
      pirce: 30,
      amount: 1,
      featuredImg: "/Images/shop-pinza-5.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 6,
      type: "pinza",
      category: "vegetarian",
      name: "The Mattar Farm Pinza",
      ingredients:
        "Tomato Sauce, Mozzarella cheese, The Mattar Farm Smoked Brisket, Caramelized Onions, Parsely, topped with Homemade Chipotle Sauce.",
      pirce: 32,
      amount: 1,
      featuredImg: "/Images/shop-pinza-6.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 7,
      type: "pinza",
      category: "meat",
      name: "Aloha Pinza",
      ingredients:
        "Tomato Sauce, Mozzarella Cheese, Pulled Beef, Caramelized Onions, Fresh Pineapple, Goat Cheese, Jalapeno, Spring Onions topped with Homemade Chipotle Sauce.",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-7.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 8,
      type: "pinza",
      category: "meat",
      name: "Feel The Beet Pinza",
      ingredients:
        "Beetroot Base, Cherry Tomato, Black Olives, Goat Cheese, Pickled Beetroot, Arugula and topped with Basil",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-8.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 9,
      type: "pinza",
      category: "vegetarian",
      name: "Shrooms",
      ingredients: "Tomato Sauce, Mozzarella, , Portobello Mushrooms, Rosemary",
      pirce: 32,
      amount: 1,
      featuredImg: "/Images/shop-pinza-9.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 10,
      type: "pinza",
      category: "meat",
      name: "Margherita 'The Classic'",
      ingredients: "Tomato Sauce, Mozzarella, Basil, Oregano",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-10.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 11,
      type: "pinza",
      category: "meat",
      name: "Truffle Goodness",
      ingredients:
        "Black Truffle Sauce, Mozzarella, Parsley, Portobello Mushrooms (No Tomato Sauce)",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-11.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 12,
      type: "pinza",
      category: "vegetarian",
      name: "Veggielicious",
      ingredients:
        "Tomato Sauce, Mozzarella, Olives, Portobello Mushrooms, Green,Red and Yellow Peppers",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-12.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 13,
      type: "pinza",
      category: "meat",
      name: "Totally Twisted",
      ingredients:
        " Cheese, Green, Red and Yellow Peppers, Black Olives, Wagyu Sausage and Basil",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-13.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 14,
      type: "pinza",
      category: "vegetarian",
      name: "Amore Alla Parmigiana",
      ingredients: "Tomato Sauce, Mozzarella, Aubergine, Basil, Parmigiano",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-14.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 15,
      type: "pinza",
      category: "meat",
      name: "El Padrino",
      ingredients: "Fresh Tomato, el padrino spicy sauce, Garlic, Chili",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-15.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 16,
      type: "pinza",
      category: "meat",
      name: "Montuori",
      ingredients:
        "Tomato Sauce, Rocca Leaves, Bresaola, “Secret” Cream, Parmigiano",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-16.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 17,
      type: "pinza",
      category: "Vegan",
      name: "Pepperoni",
      ingredients: "Tomato Sauce, Mozzarella, Pepperoni Salami",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-17.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 18,
      type: "pinza",
      category: "meat",
      name: "Pesto",
      ingredients:
        "Pesto, Wagyu Sausage, Portobello Mushrooms, Pine Nuts, Parmigiano",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-18.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 19,
      type: "pinza",
      category: "meat",
      name: "Tandoori Chicken",
      ingredients: "Tomato Sauce with Ground Masala,Tandoori Chicken",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-19.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 20,
      type: "pinza",
      category: "Vegan",
      name: "Spizy ",
      ingredients:
        "Mozzarella, Wagyu Sausage, Portobello Mushrooms, Chili Flakes, Fennel Seeds, Caramelized Onion, Tomato Sauce",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-20.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 21,
      type: "pinza",
      category: "meat",
      name: "The FAUX Meat Lover Pinza ",
      ingredients:
        "Tomato Sauce, Vegan Mozzarella Cheese, Mixed Capsicum, Black Olives, Cherry Tomatoes, Vegan Apple Maple Sausage and Fennel Seeds",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-21.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 22,
      type: "pinza",
      category: "meat",
      name: "Pinzatalia ",
      ingredients:
        "Tomato Sauce, Diced Mozarella, Cherry, Tomatoes, Fresh Onions, Seasoned Chicken, Basil",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-22.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 23,
      type: "pinza",
      category: "Vegan",
      name: "OMV - OH MY VEGAN Pinza ",
      ingredients:
        "Tomato Sauce, Vegan Mozzarella Cheese, Portobello Mushrooms, Zucchini, Caramelized Onions, Mixed Capsicum, Vegan Mexicano Chipotle Sausage ",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-23.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 24,
      type: "pinza",
      category: "meat",
      name: "Formaggio",
      ingredients:
        "Pecorino Cheese, Mozzarella, Black Pepper, fresh basil (No Tomato Sauce)",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-24.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 25,
      type: "pinza",
      category: "meat",
      name: "Amalfi  ",
      ingredients:
        "Tomato Sauce, Cherry Tomato, Zucchini, Black Olives, Caramelized Onions, Feta Cheese, Oregano",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-25.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 26,
      type: "pinza",
      category: "meat",
      name: "Truffled Vegan  ",
      ingredients:
        "Tomato Sauce, Portobello Mushrooms, Zucchini, Caramelized Onions, Vegan Mushroom Deli Slice and Vegan Truffle Sauce",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-26.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 27,
      type: "pinza",
      category: "meat",
      name: "ACAPULCO ",
      ingredients:
        "Tomato Sauce, Mozzarella Cheese, Seasoned Chicken, Grilled Peppers, Fresh Onion, topped with Fresh Mexican Guacamole, Cilantro and sour cream with a side of Fresh Mexican Salsa",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-27.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 28,
      type: "pinza",
      category: "meat",
      name: "Hangover 1 ",
      ingredients:
        "Tomato sauce,diced mozzarella, salami pepperoni,spianata piccante,onions, jalapeños, chilli flakes, wagyu sausage",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-28.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 29,
      type: "pinza",
      category: "Dessert",
      name: "Nutella Banana  ",
      ingredients:
        "Tomato Sauce, Diced Mozarella, Cherry, Tomatoes, Fresh Onions, Seasoned Chicken, Basil",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-29.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 30,
      type: "pinza",
      category: "Dessert",
      name: "Nutella Solo  ",
      ingredients:
        "Tomato Sauce, Diced Mozarella, Cherry, Tomatoes, Fresh Onions, Seasoned Chicken, Basil",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/shop-pinza-30.png",
      featured: true,
    },
  },
  {
    fields: {
      id: 31,
      type: "drink",
      category: "drink",
      name: "Sprite",
      ingredients: "350ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-1.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 32,
      type: "drink",
      category: "drink",
      name: "Sprite Diet ",
      ingredients: "350ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-2.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 33,
      type: "drink",
      category: "drink",
      name: "Water",
      ingredients: "500ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-3.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 34,
      type: "drink",
      category: "drink",
      name: "Sparkling Water",
      ingredients: "500ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-4.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 35,
      type: "drink",
      category: "drink",
      name: "Sparkling Water ",
      ingredients: "500ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-5.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 36,
      type: "drink",
      category: "drink",
      name: "Fanta",
      ingredients: "350ml",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-6.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 37,
      type: "drink",
      category: "drink",
      name: "Nai's Hibiscus Flower Tea",
      ingredients:
        'Infused with Pomegranate Rose Grape & Apple. 100% natural, "no added sugar" iced tea in 250ml single serve can',
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-7.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 38,
      type: "drink",
      category: "drink",
      name: "Nai's Jasmine White Tea ",
      ingredients:
        'Infused with Peach Mango & Pear.  100% natural, "no added sugar" iced tea in 250ml single serve can',
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-8.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 39,
      type: "drink",
      category: "drink",
      name: "Nai's Ginger Green Tea ",
      ingredients:
        'Infused with Apple.  100% natural, "no added sugar" iced tea in 250ml single serve can',
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-9.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 40,
      type: "drink",
      category: "drink",
      name: "Nai's Moroccan Mint Tea ",
      ingredients:
        'Infused with Lemon Pear & Monk Fruit.  100% natural, "no added sugar" iced tea in 250ml single serve can',
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/drink-10.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 41,
      type: "salad",
      category: "salad",
      name: "Chicken Avocado",
      ingredients:
        "Pulled chicken, avocado, shallots, spring onions, cilantro, mixed greens, cherry tomatoes. Dressing: Lime - Cilantro",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/salad-1.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 42,
      type: "salad",
      category: "salad",
      name: "Bresaola Salad",
      ingredients: "Arugula, bresaola, pecorino cheese,cherry tomatoes, ",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/salad-2.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 43,
      type: "salad",
      category: "salad",
      name: "Yummy Burrata",
      ingredients:
        "Arugula, basil,roasted peppers,cherry tomatoes, Burrata Cheese. Dressing: Truffle - Balsamic",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/salad-3.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 44,
      type: "salad",
      category: "salad",
      name: "Chicken Protein Salad",
      ingredients:
        "Mixed Greens, Arugula, Pulled Chicken, Avocado,Roasted Peppers, Cherry Tomatoes, Pine Nuts, Chickpeas, Mint Leaves, Basil, Spring Onions, Shallots, Cilantro - Balsamic Vinaigrette Dressing.",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/salad-4.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 45,
      type: "side",
      category: "side",
      name: "Avocado Hummus",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-1.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 46,
      type: "side",
      category: "side",
      name: "Crushed Mini Pototo with Harissa Mayo",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-2.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 47,
      type: "side",
      category: "side",
      name: "Beetroot Hummus",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-3.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 48,
      type: "side",
      category: "side",
      name: "Crushed Mini Potato with Truffled Burrata ",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-4.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 49,
      type: "side",
      category: "side",
      name: "Free Range Chicken Tenders (5 pcs)",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-5.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 50,
      type: "side",
      category: "side",
      name: "Free Range Chicken Tender (10 pcs)",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-6.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 51,
      type: "side",
      category: "side",
      name: "FRENCH FRIES",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-7.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 52,
      type: "side",
      category: "side",
      name: "SWEET POTATO FRIES",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-8.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 53,
      type: "side",
      category: "side",
      name: "CAJUN FRIES",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-9.png",
      featured: false,
    },
  },
  {
    fields: {
      id: 54,
      type: "side",
      category: "side",
      name: "CRISPERS",
      pirce: 24,
      amount: 1,
      featuredImg: "/Images/side-10.png",
      featured: false,
    },
  },
];
